### ISSUE TITLE
GoDaddy API returned 401 status,  update FAILED

### ISSUE THREAD

**Issue by jamess5** [parker-hemphill/godaddy-dns-updater#3]
Hi,

I'm getting this error:
`GoDaddy API returned 401 status,  update FAILED`

It seems it cannot authenticate on the API. I have the environment set up with the API key in it, but is there anywhere I need to store the API secret? I couldn't find any environment variables to insert the secret in.

Many thanks,
J.

**Comment by parker-hemphill** [comment]
I use the following in my docker-compose.yaml:
```
  godaddy:
    image: parkerhemphill/godaddy-dns-updater
    container_name: godaddy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - DOMAIN=${GODADDY_DOMAIN}
      - API_KEY=${GODADDY_API_KEY}
      - DNS_CHECK=${GODADDY_DNS_CHECK}
      - TIME_ZONE=${TZ}
    volumes:
      - /tmp:/tmp
    restart: unless-stopped
```
And in .env:
```
TZ=America/New_York
GODADDY_DOMAIN=mydomain.com
GODADDY_API_KEY=DUMMY_APIKEY_WITHOUT_QUOTES
GODADDY_DNS_CHECK=900
```
401 is an error indicating you haven't passed the correct authentication to GoDaddy.  LMK if this fixes your issue.  I'll add a conditional to call out this error in the logs in the future

**Comment by parker-hemphill** [comment]
UPDATE, I set my domain to a bogus value in GoDaddy DNS editor, verified it was resolving to that IP with `dig mydomain.com` and pruned my godaddy container and pulled the latest image.  Updated without issue so there is something wrong with how you've entered your API key

**Comment by parker-hemphill** [comment]
UPDATE 2: I threw docker onto one of my RPIs and pulled the image.  The updates fail on my pi, looks like the RPI version of alpine is missing some binaries so I'll poke at that and try to get it fixed like in the next hour

**Comment by jamess5** [comment]
Hi @parker-hemphill thanks for the response!

Unfortunately I still encounter the issue. My docker-compose.yaml extract looks like this:

```
version: "3.0"

services:

  godaddy-ddns:
    container_name: godaddy-ddns
    image: parkerhemphill/godaddy-dns-updater
    environment:
      - DOMAIN=mydomain.com
      - SUB_DOMAIN=vpn
      - API_KEY=xxxxxxxxxxxx
      - DNS_CHECK=600
      - TIME_ZONE=Europe/London
    volumes:
      - /tmp:/tmp
    restart: always
```

Do you have any further suggestions?

I'm not using a RPI - I'm using NUC. The API key I'm including without quotes etc.

Thanks,
James
